### PR TITLE
Win 8.1 fix for darcyclarke/Detect.js#48

### PR DESCRIPTION
**Pull request by AdrianoCahete**
Fix for #48

### CODE REVIEW

**Comment by AdrianoCahete** [comment]
IDK why has conflicts. If anyone can review, will be good. Otherwise, i'll undo everything and do again later.

**Comment by julmot** [comment]
@AdrianoCahete 

Just rebase your fork.

**Comment by julmot** [comment]
@AdrianoCahete Why did you close it?

**Comment by AdrianoCahete** [comment]
I did a rollback in my local repo and will do it again from original.

**Pull request closed without merging**
