### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by deificx**
I've created a test generator to build tests based on user agent strings and expected results based on  www.useragentstring.com as a source of truth. I have a bunch of common cases in the tests/cases.json file and more should be added, but I've already found a bunch of things I think are mistakes, so before adding more I think these should be addressed first. 

##### Disclaimer: Some of my expected results are probably incorrect

These were scraped from useragentstring.com and I've corrected and removed a bunch of duplicates, but there could still be errors in the test cases

#### 1) The test in the README.md doesn't seem to be correct:

```
  Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7
    ✓ browser.family
    1) browser.name
    2) browser.version
    ✓ browser.major
    ✓ browser.minor
    ✓ browser.patch
    ✓ device.family
    ✓ device.name
    ✓ device.type
    ✓ device.manufacturer
    ✓ os.family
    3) os.name
    4) os.version
    ✓ os.major
    ✓ os.minor

...

1) Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7 browser.name:

      AssertionError: expected 'Mobile Safari 4' to equal 'Mobile Safari 4.0.5'
      + expected - actual

      -Mobile Safari 4
      +Mobile Safari 4.0.5
      
      at Context.<anonymous> (tests/generatedTests.js:13:30)

  2) Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7 browser.version:

      AssertionError: expected '4' to equal '4.0.5'
      + expected - actual

      -4
      +4.0.5
      
      at Context.<anonymous> (tests/generatedTests.js:16:33)

  3) Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7 os.name:

      AssertionError: expected 'iOS 4' to equal 'iOS 4.0'
      + expected - actual

      -iOS 4
      +iOS 4.0
      
      at Context.<anonymous> (tests/generatedTests.js:43:25)

  4) Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7 os.version:

      AssertionError: expected '4' to equal '4.0'
      + expected - actual

      -4
      +4.0
      
      at Context.<anonymous> (tests/generatedTests.js:46:28)


```

#### 2) There is quite some difference in how names and family are recorded. 

For Mac OS X: (passes)
```
	"family": "Mac OS X",
	"name": "Mac OS X 10.10.1",
```

For Windows: (fails)
```
	"family": "Windows",
	"name": "Windows 98"
```

#### 3) Windows name and versions

I think the sane thing here is to use the NT name and version. see https://en.wikipedia.org/wiki/Windows_NT#Releases

There is some overlap in server and home releases and the user agent string says the NT number, which users could be referred to instead of sometimes saying windows 10, and other Windows Server 2016

I also think family always should be "Windows" for any Windows version. 

#### 4) Version field

The version field should could contain the whole version number. It quite often contains the major number only. Since the version number in full is used in name tests like this fail: name: "Chrome 41.0.2227.1", Detect returns "Chrome 41" Which could be OK, but is inconsistent with OS name and version (at least for Mac)

### CODE REVIEW

**Comment by AdrianoCahete** [comment]
Sorry for delay. I can't test right now (possibly only at the end of the month) and don't know if anyone can test ( @julmot ?) , but if you make sure it's working, we can merge your PR.

Looking at the files i don't find any problem. 

About your message:
I think ```browser.version/browser.name/os.version/os.name``` just get major version. I don't know if is by design, just @darcyclarke can answer that.

About default windows name, i agree with you.

in fact, *I* just use that lib to find OS name and browser's major version.

**Comment by deificx** [comment]
Thanks for looking at it. The only change affecting the actual library is this line: `typeof window === 'undefined' ? {} : window`, to check window exist, and if not uses an empty object. This is to make sure the code runs in the node environment which doesn't have a window. 

All the other code lives in the tests, and scripts folders. One new dependency is added `chai`, to do assertions (expect). [`istanbul`](https://www.npmjs.com/package/istanbul) is a good library to output test coverage (so could be added at a later stage).

### Instructions

To run the tests you simply run `npm test`.

To output what is being tested, run `node tests/caseCoverage.js`.

Creating more testCases requires some manual labor, but I've added a lookup.js and user_agent_parser.js to gather some data more efficiently. Fill in the array in user_agent_parser and define if the string belongs to a `Mobile`, `Tablet` or `Desktop`. Running that script saves the user agent and some expected results in a new file in the `tests/` folder named `parsed`, no extension. Copy the objects to `cases.json` and fix formatting and obvious errors.

**Comment by julmot** [comment]
Hi @deificx,

thanks for the idea of building a unit test based on external databases. I already thought about merging the databases behind other browser detection libraries for other languages into one single database. Then we could all test against the same database and guarantee a consistently library. But using useragentstring.com is another way with which I agree.

I just tested your PR and it works. However I see this prints a huge list of AsserptionErrors. If you have the time me, @darcyclarke and @AdrianoCahete don't have, you may can help to solve those issues.

Before merging please add comments about what you are doing. This helps others to contribute.

**Comment by julmot** [comment]
@deificx I'm closing this for now, as you have not responded.

**Pull request closed without merging**
